package gjum.minecraft.mapsync.common.net.packet;

import io.netty.buffer.ByteBuf;
import org.jetbrains.annotations.NotNull;

/**
 * Once this packet is received, the client will either be disconnected or
 * considered fully verified.
 *
 * @param sharedSecret 16 randomly generated bytes encrypted with the server's public key.
 * @param verifyToken The server's transaction ID encrypted with the server's public key.
 */
public record C2S_EncryptionResponsePacket(
		byte @NotNull [] sharedSecret,
		byte @NotNull [] verifyToken
) implements IPacket {
	public static final int PACKET_ID = 3;

	@Override
	public void write(final @NotNull ByteBuf buffer) {
		IPacket.writeByteArray(buffer, this.sharedSecret);
		IPacket.writeByteArray(buffer, this.verifyToken);
	}
}
