name: Build Mod

on:
  push:
    paths:
      - "mapsync-mod/**/*"
  pull_request:
    paths:
      - "mapsync-mod/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - run: ./gradlew build
        working-directory: ./mapsync-mod

      - name: Upload Forge Build
        uses: actions/upload-artifact@v3
        with:
          name: Forge
          path: mapsync-mod/dist/*-forge.jar

      - name: Upload Fabric Build
        uses: actions/upload-artifact@v3
        with:
          name: Fabric
          path: mapsync-mod/dist/*-fabric.jar

      - name: Release Tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            mapsync-mod/dist/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
