name: Build+Test Server

on:
  push:
    paths:
      - "mapsync-server/**/*"
  pull_request:
    paths:
      - "mapsync-server/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.1.17", "latest"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.version }}

      - run: bun install
        working-directory: ./mapsync-server

      - run: bun test
        working-directory: ./mapsync-server
